apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardhat-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardhat-node
  template:
    metadata:
      labels:
        app: hardhat-node
    spec:
      containers:
        - name: hardhat-node
          image: hardhat-node:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8545
